post:
  tags:
    - Products
  summary: Products Create
  description: Products description
  operationId: productcreate
  security:
    - api_key: ["test"]
    - basic_auth: []
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value: Created successfully
        application/xml:
          schema:
            type: string
        text/csv:
          schema:
            type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: '..\components\schemas\Products.yaml'
      application/xml:
        schema:
          type: string
          example: Hello world!
    description: Echo payload
    required: true
get:
  tags:
    - Products
  summary: Get all products
  description: |
    Get all the products list
  operationId: allProductsList
  security:
    - api_key: []
  responses:
    "200":
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\Products.yaml
          example:
            id: 111
            name: Product1
            description: Product Description
    "403":
      description: Forbidden
